import { Request, Response, NextFunction } from "express";
import { AuthenticatedRequest } from "../middlewares/auth.middleware";
import prisma from "../config/db";
import logger from "../utils/logger";
import os from "os";

/**
 * GET /api/admin/overview
 * Platform-wide telemetry overview for admins.
 */
export async function getAdminOverview(
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const userId = req.user?.id;
    if (!userId) {
      res.status(401).json({ success: false, message: "Unauthorized" });
      return;
    }

    const [
      totalUsers,
      activeUsers,
      premiumSubscribers,
      allPayments,
      totalVoiceGenerations,
      charStats,
      latestUsers,
      latestGenerations,
      latestPayments,
      apiUsage
    ] = await Promise.all([
      prisma.user.count({ where: { deletedAt: null } }),
      prisma.user.count({ where: { status: "Active", deletedAt: null } }),
      prisma.user.count({
        where: {
          deletedAt: null,
          OR: [
            { plan: { contains: "Pro" } },
            { plan: { contains: "Business" } },
            { plan: { contains: "Enterprise" } }
          ]
        }
      }),
      prisma.payment.findMany({ where: { status: "Paid", deletedAt: null }, select: { amount: true, createdAt: true } }),
      prisma.voiceGeneration.count({ where: { deletedAt: null } }),
      prisma.voiceGeneration.aggregate({
        where: { deletedAt: null },
        _sum: { charCount: true },
        _avg: { duration: true }
      }),
      prisma.user.findMany({ where: { deletedAt: null }, orderBy: { createdAt: "desc" }, take: 5, select: { name: true, email: true, plan: true, status: true, createdAt: true } }),
      prisma.voiceGeneration.findMany({ where: { deletedAt: null }, orderBy: { createdAt: "desc" }, take: 5, select: { user: { select: { name: true } }, voice: { select: { name: true } }, charCount: true, createdAt: true } }),
      prisma.payment.findMany({ where: { deletedAt: null }, orderBy: { createdAt: "desc" }, take: 5, select: { transactionId: true, amount: true, currency: true, createdAt: true, user: { select: { name: true } } } }),
      prisma.usageAnalytics.count()
    ]);

    // Revenue calculations
    const totalRevenue = allPayments.reduce((sum, p) => sum + p.amount, 0);
    const startOfMonth = new Date();
    startOfMonth.setDate(1);
    startOfMonth.setHours(0, 0, 0, 0);
    const monthlyRevenue = allPayments
      .filter(p => p.createdAt >= startOfMonth)
      .reduce((sum, p) => sum + p.amount, 0);

    // DB health check
    const startDb = Date.now();
    await prisma.$queryRaw`SELECT 1`;
    const dbLatency = Date.now() - startDb;

    // CPU and Memory load
    const cpuLoad = os.loadavg()[0];
    const totalMemBytes = os.totalmem();
    const freeMemBytes = os.freemem();
    const usedMemBytes = totalMemBytes - freeMemBytes;

    const systemHealth = {
      db: { status: "HEALTHY", latencyMs: dbLatency },
      neuralEngine: { status: "HEALTHY", latencyMs: 120 }, // Mock ElevenLabs latency
      redis: { status: "HEALTHY", latencyMs: 1 },
      cpuUsagePercent: parseFloat(((cpuLoad / os.cpus().length) * 100).toFixed(1)),
      memoryUsedGB: parseFloat((usedMemBytes / (1024 ** 3)).toFixed(1)),
      memoryTotalGB: parseFloat((totalMemBytes / (1024 ** 3)).toFixed(1))
    };

    // Combine recent activities
    const activityFeed: any[] = [];
    latestUsers.forEach(u => {
      activityFeed.push({
        text: `New user signup: ${u.name} (${u.plan})`,
        icon: "user-plus",
        type: "secondary",
        createdAt: u.createdAt
      });
    });
    latestGenerations.forEach(g => {
      activityFeed.push({
        text: `Audio clip generated by ${g.user?.name || "User"} using ${g.voice?.name || "Voice"} (${g.charCount} chars)`,
        icon: "music",
        type: "primary",
        createdAt: g.createdAt
      });
    });
    latestPayments.forEach(p => {
      activityFeed.push({
        text: `Stripe payment processed: $${p.amount.toFixed(2)} ${p.currency} (Ref: ${p.transactionId})`,
        icon: "credit-card",
        type: "success",
        createdAt: p.createdAt
      });
    });

    activityFeed.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
    const finalFeed = activityFeed.slice(0, 10).map(item => {
      const diffMs = Date.now() - item.createdAt.getTime();
      const diffMins = Math.floor(diffMs / 60000);
      let timeStr = "Just Now";
      if (diffMins > 0) {
        if (diffMins < 60) timeStr = `${diffMins} mins ago`;
        else {
          const diffHours = Math.floor(diffMins / 60);
          if (diffHours < 24) timeStr = `${diffHours} hours ago`;
          else timeStr = item.createdAt.toLocaleDateString();
        }
      }
      return { text: item.text, icon: item.icon, type: item.type, time: timeStr };
    });

    res.status(200).json({
      success: true,
      data: {
        kpis: {
          totalUsers,
          activeUsers,
          premiumSubscribers,
          totalRevenue,
          monthlyRevenue,
          totalVoiceGenerations,
          avgDuration: charStats._avg.duration || 0,
          totalChars: charStats._sum.charCount || 0,
          apiUsage
        },
        systemHealth,
        activityFeed: finalFeed,
        recentSignups: latestUsers.map(u => ({
          name: u.name,
          email: u.email,
          plan: u.plan,
          status: u.status,
          registered: u.createdAt.toLocaleString()
        }))
      }
    });
  } catch (error) {
    logger.error(`[Admin Controller Overview] Error: ${(error as Error).message}`);
    next(error);
  }
}

/**
 * GET /api/admin/users
 * Paginated and filtered users list.
 */
export async function getAdminUsers(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 10;
    const search = (req.query.search as string || "").trim().toLowerCase();
    const plan = req.query.plan as string || "all";
    const status = req.query.status as string || "all";

    const whereClause: any = { deletedAt: null };

    // Search filter
    if (search) {
      whereClause.OR = [
        { name: { contains: search } },
        { email: { contains: search } }
      ];
    }

    // Plan filter
    if (plan !== "all") {
      whereClause.plan = { contains: plan };
    }

    // Status filter
    if (status !== "all") {
      whereClause.status = status;
    }

    const skip = (page - 1) * limit;

    const [users, total] = await Promise.all([
      prisma.user.findMany({
        where: whereClause,
        orderBy: { createdAt: "desc" },
        skip,
        take: limit,
        select: {
          id: true,
          name: true,
          email: true,
          plan: true,
          status: true,
          createdAt: true,
          _count: {
            select: { generations: true }
          }
        }
      }),
      prisma.user.count({ where: whereClause })
    ]);

    const totalPages = Math.ceil(total / limit);

    res.status(200).json({
      success: true,
      data: {
        users: users.map(u => ({
          id: u.id,
          name: u.name,
          email: u.email,
          plan: u.plan,
          registered: u.createdAt.toLocaleDateString(),
          status: u.status,
          generationsCount: u._count.generations
        })),
        total,
        page,
        totalPages
      }
    });
  } catch (error) {
    logger.error(`[Admin Controller Users] Error: ${(error as Error).message}`);
    next(error);
  }
}

/**
 * GET /api/admin/users/:id
 * Retrieve details for a specific user.
 */
export async function getAdminUserDetails(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const { id } = req.params;

    const user = await prisma.user.findFirst({
      where: { id, deletedAt: null },
      include: {
        subscriptions: { where: { deletedAt: null }, orderBy: { createdAt: "desc" } },
        payments: { where: { deletedAt: null }, orderBy: { createdAt: "desc" } },
        _count: {
          select: { generations: true }
        }
      }
    });

    if (!user) {
      res.status(404).json({ success: false, message: "User not found" });
      return;
    }

    res.status(200).json({
      success: true,
      data: {
        id: user.id,
        name: user.name,
        email: user.email,
        plan: user.plan,
        status: user.status,
        registered: user.createdAt.toLocaleString(),
        generationsCount: user._count.generations,
        subscriptions: user.subscriptions,
        payments: user.payments
      }
    });
  } catch (error) {
    logger.error(`[Admin Controller User Details] Error: ${(error as Error).message}`);
    next(error);
  }
}

/**
 * PUT /api/admin/users/:id/status
 * Suspend or activate a user account.
 */
export async function updateAdminUserStatus(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const { id } = req.params;
    const { status } = req.body;

    if (status !== "Active" && status !== "Suspended") {
      res.status(400).json({ success: false, message: "Invalid status" });
      return;
    }

    const updatedUser = await prisma.user.update({
      where: { id },
      data: { status }
    });

    res.status(200).json({
      success: true,
      message: `User status set to ${status}`,
      data: updatedUser
    });
  } catch (error) {
    logger.error(`[Admin Controller User Status] Error: ${(error as Error).message}`);
    next(error);
  }
}

/**
 * PUT /api/admin/users/:id/plan
 * Update plan and subscription details.
 */
export async function updateAdminUserPlan(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const { id } = req.params;
    const { plan } = req.body;

    const normalizedPlan = plan.replace(" Plan", "");

    const updatedUser = await prisma.user.update({
      where: { id },
      data: { plan }
    });

    const creditLimit = plan.includes("Pro") ? 150000 : plan.includes("Starter") ? 50000 : plan.includes("Enterprise") ? 10000000 : 10000;
    
    // Mark previous subscriptions expired
    await prisma.subscription.updateMany({
      where: { userId: id, status: "Active" },
      data: { status: "Expired" }
    });

    // Create a new subscription cycle
    await prisma.subscription.create({
      data: {
        userId: id,
        plan: normalizedPlan,
        status: "Active",
        creditLimit,
        creditUsed: 0,
        endDate: new Date(Date.now() + 30 * 24 * 3600 * 1000)
      }
    });

    res.status(200).json({
      success: true,
      message: `User plan upgraded to ${plan}`,
      data: updatedUser
    });
  } catch (error) {
    logger.error(`[Admin Controller User Plan] Error: ${(error as Error).message}`);
    next(error);
  }
}

/**
 * DELETE /api/admin/users/:id
 * Soft delete user.
 */
export async function deleteAdminUser(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const { id } = req.params;

    await prisma.user.update({
      where: { id },
      data: {
        deletedAt: new Date(),
        status: "Suspended"
      }
    });

    res.status(200).json({
      success: true,
      message: "User account soft deleted successfully"
    });
  } catch (error) {
    logger.error(`[Admin Controller Delete User] Error: ${(error as Error).message}`);
    next(error);
  }
}

// ==========================================
// VOICE CATALOG MANAGEMENT
// ==========================================
export async function getAdminVoices(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    const voices = await prisma.voice.findMany({
      where: { deletedAt: null },
      orderBy: { createdAt: "desc" }
    });
    res.status(200).json({ success: true, data: voices });
  } catch (error) {
    next(error);
  }
}

export async function addAdminVoice(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    const { name, lang, gender, accent, style, featured } = req.body;
    
    // Check if voice name exists
    const existing = await prisma.voice.findUnique({ where: { name } });
    if (existing) {
      res.status(400).json({ success: false, message: "Voice name already exists." });
      return;
    }

    const newVoice = await prisma.voice.create({
      data: {
        name,
        gender: gender || "Female",
        category: style || "Standard",
        accent: accent || "Global",
        age: "Adult",
        featured: featured || false,
        providerName: "local"
      }
    });
    res.status(201).json({ success: true, data: newVoice });
  } catch (error) {
    next(error);
  }
}

export async function updateAdminVoice(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = req.params;
    const { name, featured } = req.body;
    
    const existing = await prisma.voice.findUnique({ where: { id } });
    if (!existing) {
      res.status(404).json({ success: false, message: "Voice not found." });
      return;
    }

    const updated = await prisma.voice.update({
      where: { id },
      data: {
        name: name !== undefined ? name : existing.name,
        featured: featured !== undefined ? featured : existing.featured
      }
    });
    res.status(200).json({ success: true, data: updated });
  } catch (error) {
    next(error);
  }
}

export async function deleteAdminVoice(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = req.params;
    await prisma.voice.update({
      where: { id },
      data: { deletedAt: new Date() }
    });
    res.status(200).json({ success: true, message: "Voice deleted." });
  } catch (error) {
    next(error);
  }
}

export async function getAdminPayments(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    const payments = await prisma.payment.findMany({
      include: { user: { select: { name: true, email: true } } },
      orderBy: { createdAt: "desc" }
    });
    res.status(200).json({ success: true, data: payments });
  } catch (error) { next(error); }
}

export async function approveAdminPayment(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = req.params;
    const payment = await prisma.payment.findUnique({ where: { id } });
    if (!payment || payment.status === "Paid") {
      res.status(400).json({ success: false, message: "Invalid payment" });
      return;
    }
    
    // Mark as paid
    await prisma.payment.update({ where: { id }, data: { status: "Paid" } });
    
    // Automatically upgrade the user (assume Pro Plan for demo if we don't know the exact plan here)
    const user = await prisma.user.update({
      where: { id: payment.userId },
      data: { plan: "Pro Plan" }
    });

    // Create Subscription
    const nextMonth = new Date();
    nextMonth.setMonth(nextMonth.getMonth() + 1);
    await prisma.subscription.updateMany({
      where: { userId: user.id, status: "Active" },
      data: { status: "Canceled" }
    });
    await prisma.subscription.create({
      data: {
        userId: user.id,
        plan: "Pro Plan",
        status: "Active",
        creditLimit: 500000,
        creditUsed: 0,
        startDate: new Date(),
        endDate: nextMonth
      }
    });

    res.status(200).json({ success: true, message: "Payment approved and user upgraded" });
  } catch (error) { next(error); }
}
